### PR TITLE
show virtualenv inside galaxyline

### LINKED ISSUE #732: Python virtual env in galaxyline

### PR DESCRIPTION
**Pull request by abzcoding**
Fixes #732 
@ChristianChiarulli  did you have something like this in mind?
venv

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
yes, this is very cool

**Comment by abzcoding** [comment]
so only activate it when we have python virtualenv or you want to have something similar for like rvm and others as well?

**Comment by ChristianChiarulli** [comment]
probably good to stick to python as a first pass, also does this support conda?

**Comment by abzcoding** [comment]
@ChristianChiarulli  now it does, can you test it on your end and see if you like it or not?

**Comment by ChristianChiarulli** [comment]
Just tested, it looks great, do you think this is ready?

**Comment by abzcoding** [comment]
yep I think it's ready

**Pull request merged**
