### PR TITLE
User configurable latex lsp#2

### PR DESCRIPTION
**Pull request by PZ31k0nauT**
### Description

This PR makes the latex lsp more flexible and easier to configure. Almost every setting can be made in lv-config.lua. With those the user can choose which build arguments and which preview options are to be used by lunarvim.

My hope is that this is a desired PR in the light of #638.

Disclaimer: This is a copy of #671, which has been closed by me. I've messed up big time I think. The main difference is that this PR is now based on rolling and has a cleaner commit history. I'm still learning sorry for the inconvenience.

#### Type Of Change

Please check the relevant options.

- Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality
- Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update (maybe)

#### How has this been tested

- I have tested these changes with opening .tex and .bib files and checking for linting and lsp-autocomplete. It's working as expected.
- I built files with the command `:TexlabBuild` successfully.
- I also previewed .tex files with the command `:TexlabForward`. Only tested Zathura.
- I switched the settings for build and preview on save. They work as desired.

#### Checklist:

- [x] I read the contributing guide
- [x] My code follows the style guidelines of the project (at least I hope so)
- [x] I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas (code is pretty straightforward)
- [x] I have made corresponding changes to the documentation (I would but I don't know where)
- [x] My changes generate no warnings

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
This looks great, let me know when you think it's ready, and we'll get it merged.

**Comment by PZ31k0nauT** [comment]
I took the freedom to add `:TexlabBuild` and `:TexlabForward` to the +Latex which-key category.

I also changed the which-key for +Latex from `L` to `t` (for tex), because L is conflicting with +Lush.

When `t` is a good choice this PR is good to go.

On question for me is, if and where I should put documentation. In my old PR I had all options listed in the lv-config.example.lua:

```lua
--LaTeX
O.lang.latex.active = true
O.lang.latex.aux_directory = "."
O.lang.latex.bibtex_formatter = "texlab"
O.lang.latex.build.args = { '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f' }
O.lang.latex.build.executable = "latexmk" 
O.lang.latex.build.forward_search_after = false
O.lang.latex.build.on_save = false
O.lang.latex.chktex.on_edit = false
O.lang.latex.chktex.on_open_and_save = false
O.lang.latex.diagnostics_delay = 300
O.lang.latex.formatter_line_length = 80
-- ForwardSearch for preview;
-- see https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md for options
-- insert the executable as referenced in previewng.md; lunarvim will make the rest
O.lang.latex.forward_search.executable = "zathura"
O.lang.latex.latex_formatter = "latexindent"
O.lang.latex.latexindent.modify_line_breaks = false
```

But I don't want to bloat that file. Should I put it somewhere else?

**Review by Tastyep — APPROVED** [review]

**Comment by Tastyep** [comment]
> But I don't want to bloat that file. Should I put it somewhere else?

IMO you only need to have this link on top: https://github.com/latex-lsp/texlab/blob/master/docs/options.md
The previewing options aren't super necessary since you already preconfigured them for each viewer

Good job :+1:

**Comment by PZ31k0nauT** [comment]
Ok. Then I will add those to the example file.

With all the language stuff a separate example-file with all configuration options could be useful.

**Comment by Tastyep** [comment]
Arf, there are now merge and duplicate commits :(
Please run this
```
git fetch upstream <- replace this with the name of the remote you set up
git rebase -i upstream/rolling <- change 'pick' to 'd' for commits you want to drop
Once completed (it says you need to pull, don't)
git push -f
```

**Comment by PZ31k0nauT** [comment]
Sorry again. I still have a lot to learn in the PR game.

I think it did it correctly. I think it worked only 4 commits are shown.

I hope I got it now. Thanks a lot for your help. I will write those commands down.

**Review by Tastyep — APPROVED** [review]

**Review by abzcoding — APPROVED** [review]
wonderful 💯

**Pull request merged**
