### PR TITLE
Add borders to lsp popups

### LINKED ISSUE #677: Borders for lsp popups

### PR DESCRIPTION
**Pull request by kjssad**
Attempt to fix #677.

### CODE REVIEW

**Comment by rebuilt** [comment]
borders

**Comment by rebuilt** [comment]
borders2

**Comment by rebuilt** [comment]
Border option set to 'double'

border-double

**Comment by rebuilt** [comment]
Border option set to 'shadow'

border-shadow

**Comment by IndianBoy42** [comment]
Feels like this should be configurable, maybe `O.lsp_border` or `O.popups` with more styling options

**Comment by rebuilt** [comment]
Probably have to narrow the scope if you're making it configurable. 

```
O.lsp.border
```

**Comment by kjssad** [comment]
This could be configurable but the current implementation is limited. There's no way to change the border highlights other than changing `FloatBorder`. Tho we can technically define our own border styles with specific highlights.

**Review by rebuilt — APPROVED** [review]

**Pull request merged**
