### PR TITLE
Documentation: Add sections 'Troubleshooting installation problems',

### PR DESCRIPTION
**Pull request by rebuilt**
Documentation: Add sections 'Troubleshooting installation problems', 'Community links'.  Modify section for clarity 'Install your own plugins'

### CODE REVIEW

**Comment by rebuilt** [comment]
I'm not sure all the community links are required but I put everything in there just in case.  For instance, I'm not sure how useful the github link is.  I'm ok with deleting any of those links or the entire section.

**Comment by rmagillxyz** [comment]
> Documentation: Add sections 'Troubleshooting installation problems', 'Community links'. Modify section for clarity 'Install your own plugins'

I think a section called 'Manually Install' would be useful. Just listing all the packages/steps done by the installer script in a generic form.

**Comment by rebuilt** [comment]
> I think a section called 'Manually Install' would be useful. Just listing all the packages/steps done by the installer script in a generic form.

I'm not sure if the generic form will be useful.  For instance, look at the difference between the generic and Ubuntu-specific instructions below.

# Install xclip, python3, ripgrep, fzf, npm, nodejs, pip, and ranger with the package manager for your distribution.

# Ubuntu installation
sudo apt install xclip python3-pip npm nodejs ripgrep fzf ranger libjpeg8-dev
zlib1g-dev python-dev python3-dev libxtst-dev python3-pip


The rest of the install instructions work on most other distributions

# install tree-sitter
sudo npm install -g tree-sitter-cli

# install ueberzug, neovim-remote, and pynvim with pip3
pip3 install ueberzug neovim-remote pynvim --user

# Clone LunarVim and Packer. 
git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
git clone https://github.com/ChristianChiarulli/lunarvim.git ~/.config/nvim

# Install plugins
nvim -u $HOME/.config/nvim/init.lua +PackerInstall

**Comment by rebuilt** [comment]
> I think a section called 'Manually Install' would be useful. 

I added the manual install section.  I tested the instructions for arch, ubuntu and fedora.  I don't have a mac or the time to learn gentoo so I added those sections verbatim without testing.

**Comment by rmagillxyz** [comment]
> > I think a section called 'Manually Install' would be useful.
> 
> I added the manual install section. I tested the instructions for arch, ubuntu and fedora. I don't have a mac or the time to learn gentoo so I added those sections verbatim without testing.

I like it. If someone isn't on one of those distros, they should have enough info on the README to install the appropriate packages without opening the installer script (which is what I usually do). The installer script is great when it works, but when you do it by hand, you normally know exactly where things went wrong, if they do.

**Pull request merged**
