### PR TITLE
[Feature] add linter support

### LINKED ISSUE #797: Potentially replace efm with nvim-lint
https://github.com/mfussenegger/nvim-lint

### PR DESCRIPTION
**Pull request by Tastyep**
# Description

Add [nvim-lint](https://github.com/mfussenegger/nvim-lint) dependency and configurations for the [supported](https://github.com/mfussenegger/nvim-lint#available-linters) linters.
While still in early development, the work looks promising and extensible (I might try to add clang-tidy).

Fixes #797 

## How Has This Been Tested?

Open a file and save.

I've tested all languages except HTML and Ruby, so if someone can take care of it and confirm it works, that would be great :+1: 
Also I removed some of the efm configurations since they seemed redundant with the work done by the formatter and linter plugins, if someone can double-check that it would be nice too.

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
is it possible to lint without saving?

**Comment by Tastyep** [comment]
> is it possible to lint without saving?

Probably, it would be a good idea to also run it when opening the file.
These are the events on which the command can be run
https://neovim.io/doc/user/autocmd.html  search "5. Events"

However, I'm afraid that for some languages (C++ for instance), continuous linting would be too demanding.

**Comment by abzcoding** [comment]
if there are multiple linter defined for a language, does` nvim-lint` use all of them? or the first one it finds on the system or?

**Comment by Tastyep** [comment]
> if there are multiple linter defined for a language, does` nvim-lint` use all of them? or the first one it finds on the system or?

All of them

**Comment by abzcoding** [comment]
> > if there are multiple linter defined for a language, does` nvim-lint` use all of them? or the first one it finds on the system or?
> 
> All of them

would be nice if we can disable the linting or make it on demand like how the formatting works with 
`O.format_on_save` and `<leader>lf`

**Review by abzcoding — APPROVED** [review]
LGTM :rocket:

**Comment by ChristianChiarulli** [comment]
Will you be adding anymore or should we merge?

**Comment by Tastyep** [comment]
This should be ready, I can always make a new PR to add support for other linters.
My last concern is that for python it reports A LOT since there are many configured linters.

**Comment by abzcoding** [comment]
> This should be ready, I can always make a new PR to add support for other linters.
> My last concern is that for python it reports A LOT since there are many configured linters.

for python can we keep only one of them and add a sample to `lv-config.example.lua` and how to change it or add more?

**Comment by ChristianChiarulli** [comment]
if the python linters aren't installed then they shouldn't be active tho right? Like if you only have flake8 then that's all that will show up.

**Comment by Tastyep** [comment]
> if the python linters aren't installed then they shouldn't be active tho right? Like if you only have flake8 then that's all that will show up.

That's true, we should probably aim for maximum support and let virtual environments do this job.
I'll still add an example in the lv-config.example files

**Comment by ChristianChiarulli** [comment]
I think this should be ready, I'm going to leave a not that we can get async linting by running the linter on the `TextChanged` or 
`InsertLeave` events.

**Pull request merged**
