### PR TITLE
lazyload telescope

### PR DESCRIPTION
**Pull request by kylo252**
Use lazy-loading for telescope to gain some performance.

### CODE REVIEW

**Comment by rebuilt** [comment]
I tested this pull request.  Lazy loading telescope breaks telescope-project.nvim.  You'll need to load telescope before telescope-project.nvim.  

<space>p is the shortcut for telescope-project.  It only works after the first time telescope is used.  Otherwise it fails.

**Comment by rebuilt** [comment]
I'm not sure how to verify telescope-fzy-native.nvim is working correctly

**Comment by rebuilt** [comment]
This seems to prevent telescope-project from blowing up.
```
        after = "telescope.nvim",
```

**Comment by ChristianChiarulli** [comment]
@rebuilt with any luck fzy is just ignored if not present, @kylo252 can you add the after field for telescope project so we can merge this?

**Comment by kylo252** [comment]
> @rebuilt with any luck fzy is just ignored if not present, @kylo252 can you add the after field for telescope project so we can merge this?

Sorry about not getting back to you in time. I was away all day yesterday and I didn't have access to my computer. 

I don't use fzy but I didn't need to make any adjustments to `telescope-fzf-native.nvim` and it appears to work fine.

**Pull request merged**
