### PR TITLE
Add flutter-tools

### PR DESCRIPTION
**Pull request by pxsanghyo**
- Auto-format on save for dart
- Add flutter-tools plugin
- Create flutter-tools module with default settings
- Require flutter-tools module

### CODE REVIEW

**Review by rebuilt — CHANGES_REQUESTED** [review]
The 'if' condition check in dart.lua is incorrect.  It's checking for python, not dart. 

```
-- line 13
 if O.lang.python.autoformat then
```

Also, let's try to keep init.lua slim by moving the require('lv-flutter-tools') to the plugins.lua file.  For example, this is what it looks like for compe

```
    use {
        "hrsh7th/nvim-compe",
        config = function()
            require("lv-compe").config()
        end
    }
```

**Review by rebuilt — APPROVED** [review]

**Comment by ChristianChiarulli** [comment]
flutter tools should have a disable block like rust-tools

**Comment by spareblock** [comment]
sorry, first pr... i fixed the issue but i kept getting conflicts and now it says i changed 70+ files lol... should i do another from scratch?

**Comment by pxsanghyo** [comment]
Sorry, going to close and reopen...

**Pull request closed without merging**
