### PR TITLE
Adds the ability to toggle on/off whichkey and dashboard

### PR DESCRIPTION
**Pull request by rebuilt**
Adds the ability to toggle on/off whichkey and dashboard.  Leaves them on by default.  On my machine the startup time with both on is 166ms both off is 130ms.  Also, whichkey default keybinds overwrite the 'c' bind.  

Partially addresses #336

### CODE REVIEW

**Comment by rebuilt** [comment]
If you're checking out this branch to test, you may have to re-run :PackerCompile, :PackerInstall since the packer_compiled.vim file won't match the changes you bring in through the checkout.

**Comment by folke** [comment]
@rebuilt I've made some big improvements on performance when loading the plugin. Should take around 2ms to 5ms now.

**Comment by rebuilt** [comment]
@folke 

Thanks for all your work on whichkey.  I've noticed how responsive you've been to your users requests.  

Honestly, I didn't like the old whichkey because it was incompatible with so many plugins (a lot of tpope plugins)  
But your version of whichkey is excellent and so far it's been compatible with all the plugins I've tested.

**Comment by folke** [comment]
Thanks man. Glad you like it!

**Pull request merged**
