### PR TITLE
Disable tab completion for markdown

### LINKED ISSUE #1121: [Bug]: Can't properly insert tabs/spaces with the tab key in Markdown files
### Problem description

**Steps to reproduce**
- Open a markdown file.
- Enter insert mode.
- Press the minus/dash key.
- Press the tab key.

**Expected behavior**
- Following the tab key press, a tab or spaces (depending on the indentation settings) is inserted.
- When an autocomplete suggestion list pops up though, cycling with the tab key should be possible.

**Actual behavior**

- Bad: An autocomplete suggestions list pops up.
- Bad: Nothing is inserted after the dash.
- Good: Cycling works with the tab key.

**Observations**
I noticed this is due to the hardcoded keybinds in lua/core/compe.lua:
```lua
vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", { expr = true })
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", { expr = true })
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", { expr = true })
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", { expr = true })
```

Commenting out the two insert mode keybinds allows me to enter a tab/spaces, but it comes at a downside. It then no longer seems possible to cycle through the suggestions with the tab key. Cycling is still possible using the arrow keys.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0 (stable)

### Relevant log output

_No response_

### Screenshots

image

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Disable tab completion for markdown

Fixes #1121

### CODE REVIEW

**Comment by abzcoding** [comment]
@etienne-k, can you test if this fixes your issue?

**Comment by rebuilt** [comment]
This doesn't alter the mapping.  The output of `:verbose imap <TAB>` stays the same

```
<Tab>       v:lua.tab_complete()
```

**Comment by rebuilt** [comment]
Setting it manually with `:imap <tab> <tab>` works.

**Comment by abzcoding** [comment]
> This doesn't alter the mapping. The output of `:verbose imap <TAB>` stays the same
> 
> ```
> <Tab>       v:lua.tab_complete()
> ```

have you checked this inside a markdown file
the following are the results of
```vim
:verbose imap <TAB>
:verbose map <TAB>
```
Screen Shot 2021-07-27 at 10 55 56 AM

Screen Shot 2021-07-27 at 10 56 48 AM

**Comment by rebuilt** [comment]
markdown

**Comment by abzcoding** [comment]
can you test it again 🥺

**Comment by rebuilt** [comment]
It still doesn't work. It looks like it should.  Maybe it works for you because you've modified the terminal code sent for tab?   

That being said.  It looks like it should work.  The mapping is being modified.  `verbose imap <tab>` reports the correct mapping.  I'm not sure why it doesn't work for me.

`enew | pu=execute('autocmd')`
```
_markdown  FileType
    markdown  setlocal wrap
              setlocal spell
              map <Tab> <Tab>
              map <S-Tab> <S-Tab>
              imap <Tab> <Tab>
              imap <S-Tab> <S-Tab>
```
I will post a gif

**Comment by rebuilt** [comment]
markdown

**Comment by abzcoding** [comment]
well i think it is better to just not use `<Tab>` 
this will probably cause more damage than good 😅 
i'm gonna close this PR, so can think of a better way for completion

**Comment by rebuilt** [comment]
Setting it manually in the buffer works `:imap <tab> <tab>`

**Comment by abzcoding** [comment]
> It still doesn't work. It looks like it should. Maybe it works for you because you've modified the terminal code sent for tab?
> 

I've modified the code sent for `<c-i>` , I have not touched `tab`

**Comment by rebuilt** [comment]
I don't think there's a problem with your code.  I think there's a problem with filetype detection.  I'm not sure if this is a problem with my machine or lunarvim.   I added this to my lv-config.lua

```
local file_type = vim.fn.expand("%:e")
print("Filetype is detected as " .. file_type)
if file_type ~= "markdown" then
	print("filetype is not markdown ")
else
	print("filetype is markdown ")
end
```

The result is:
```
Filetype is detected as md
filetype is not markdown
```

**Comment by abzcoding** [comment]
@rebuilt can you test the latest commit?

**Comment by rebuilt** [comment]
I pushed my suggested changes to your [personal repo](https://github.com/abzcoding/LunarVim/pull/1).  Look them over and tell me what you think.  If you can think of any other text files this behavior should apply to, add them to the list in the is_text_file function

**Comment by abzcoding** [comment]
> I pushed my suggested changes to your [personal repo](https://github.com/abzcoding/LunarVim/pull/1). Look them over and tell me what you think. If you can think of any other text files this behavior should apply to, add them to the list in the is_text_file function

i think that is actually a better solution, 
i'm closing this in favor of that
can you do a new PR to this repo instead of mine

**Pull request closed without merging**
