### PR TITLE
[KEYBINDINGS] Navigate quick-fix list with [q and ]q

### PR DESCRIPTION
**Pull request by jameswalmsley**
As seen on ThePrimeagen

This one is awesome.

### CODE REVIEW

**Comment by rebuilt** [comment]
Doesn't this override the window movement mappings?

```
vim.api.nvim_set_keymap('n', '<C-h>', '<C-w>h', {silent = true})
vim.api.nvim_set_keymap('n', '<C-j>', '<C-w>j', {silent = true})
vim.api.nvim_set_keymap('n', '<C-k>', '<C-w>k', {silent = true})
vim.api.nvim_set_keymap('n', '<C-l>', '<C-w>l', {silent = true})
```

**Comment by jameswalmsley** [comment]
@rebuilt you are right. In my config I've disabled the window nav bindings.

I'd like to get the qf navigate upstreamed.. but I'd be happy to change my personal binding.

Any suggestions for an alternative (I'll fix the PR it's git another commit mixed in).

**Comment by jameswalmsley** [comment]
Ok I've changed my binding to C-A-j C-A-k
I actually like that.

J

**Comment by rebuilt** [comment]
I think that's a natural binding.  

If you were trying to stick to vim conventions [q would also be reasonable.  A lot of the square bracket mappings already have this convention of navigating to the next/previous item.  

```
|[(|		[(		1  cursor N times back to unmatched '('
|[[|		[[		1  cursor N sections backward
|[s|		[s		1  move to the previous misspelled word
|[z|		[z		1  move to start of open fold
|[/|		[/		1  cursor to N previous start of a C comment

... etc
```

**Review by rebuilt — APPROVED** [review]

**Comment by jameswalmsley** [comment]
That sounds like a good idea.. I'll look into how you do that.. I think the C-A-jk is good natural binding..

Might be nice to map to the [q for more advanced vim users too.

**Comment by jameswalmsley** [comment]
Fixed up PR conflicts.

**Review by jameswalmsley — COMMENTED** [review]
Actually C-A-k doesnt work over ssh for some reason..
I'm looking to to the [q binding instead!

**Comment by jameswalmsley** [comment]
Ok I'm going the whole way with [q ]q 
Its much better :) thanks @rebuilt

**Pull request merged**
