### PR TITLE
User config for nvim-tree

### PR DESCRIPTION
**Pull request by Henrik-N**
Added user config for the predefined plugin nvim-tree.

### CODE REVIEW

**Comment by jameswalmsley** [comment]
Hey @Henrik-N I added a PR for configurable nvim_tree_side just as you pushed this :)
Your's is the one to land, however if you take a look at my PR there's a check left side to change the barbar offset...

i.e. only do it if nvim_tree is left aligned.

**Comment by Henrik-N** [comment]
Nice catch, I've added that change now! :)
Found a magic number in there as well that had escaped us both, so I fixed that as well :)

**Review by jameswalmsley — APPROVED** [review]

**Comment by abzcoding** [comment]
Thank you for this wonderful PR @Henrik-N, is there any chance of trimming the commits into one 🥺

**Review by jameswalmsley — APPROVED** [review]

**Comment by jameswalmsley** [comment]
> Thank you for this wonderful PR @Henrik-N, is there any chance of trimming the commits into one 🥺

It'll be squashed when Chris presses the merge button right?

**Comment by abzcoding** [comment]
> > Thank you for this wonderful PR @Henrik-N, is there any chance of trimming the commits into one 🥺
> 
> It'll be squashed when Chris presses the merge button right?

all gucci then 🎉

**Comment by vlcinsky** [comment]
Shall we do anything about the conflicting files?

To me it seems like the PR has all the stuff done properly. Would some rebase or whatever make accepting this PR simpler?

**Comment by abzcoding** [comment]
> Shall we do anything about the conflicting files?
> 
> To me it seems like the PR has all the stuff done properly. Would some rebase or whatever make accepting this PR simpler?

@vlcinsky use can change the nvimtree options in `rolling` without this PR
just do
```lua
-- lv-config.lua

O.plugin.nvim.side = "right"
-- or any other config you want
```

**Comment by abzcoding** [comment]
nvim-tree is already user-configurable through `lua/core/nvimtree.lua`->`M.config` function

**Pull request closed without merging**
