### PR TITLE
Add flutter support. Which-key included.

### PR DESCRIPTION
**Pull request by andremeireles**
Lsp will work on single dart files if `O.lang.dart.sdk_path="/home/path/to/analysis_server.dart.snapshot"` is defined.
Lsp will work on flutter projects if `O.lang.dart.flutter_tools.active = true` is defined.
If flutter-tools is active, not needed to set the sdk.
It does format on save.

Which-key has Flutter specific commands: `Space + Shift + F`.
The shortcut still showing on non-related files. Need improvements.

This solves duplicated Lsp. No more dartls, dartls showing at galaxyline.

### CODE REVIEW

**Comment by pxsanghyo** [comment]
does it format on save?

**Comment by andremeireles** [comment]
> does it format on save?

Yes.

**Comment by pxsanghyo** [comment]
shift+k (for the popup info on widgets) doesn't work for me... is it working for you?

**Comment by andremeireles** [comment]
> shift+k (for the popup info on widgets) doesn't work for me... is it working for you?

This shortcut works with coc-flutter for sure.
I never tried it with flutter-tools because isn't described in README.md

**Comment by UltimateOmega** [comment]
@ChristianChiarulli 
Hi. Can you merge this one?

**Comment by pxsanghyo** [comment]
@andremeireles intellisense (shift+k) worked before with flutter tools (about a week ago) but sh*t moves fast and now it's broken with your PR. And since intellisense works for other languages except dart, I'm wondering...
Is there something you didn't wire up to get it to work with dart?

**Comment by pxsanghyo** [comment]
@andremeireles cursor over word + :lua vim.lsp.buf.hover() shows intellisense.
It's in lua/lsp/init.lua

**Comment by UltimateOmega** [comment]
@abzcoding Can you close this one too?
in favor of #974.

**Comment by abzcoding** [comment]
Closed in favor of #974

**Pull request closed without merging**
