### PR TITLE
splits up the settings file.  settings.lua gets required before lv-co…

### PR DESCRIPTION
**Pull request by rebuilt**
Splits up the settings file.  settings.lua remains required before lv-config.   toggleable-settings depends on lv-config settings and must be required after.

Re-enables these configuration options:
lvim.line_wrap_cursor_movement
lvim.transparent_window

Fixes #(issue)
https://github.com/ChristianChiarulli/LunarVim/issues/1088

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
we could split settings into functions and call at different times?

**Comment by ichigo-gyuunyuu** [comment]
The pattern followed so far is first load `lv-config`, then in all other places we read the options in `lv-config` and proceed accordingly. If we wanted to follow that pattern, we need to expose an lvim setting to override `vim.opt` stuff.

**Comment by rebuilt** [comment]
I'll rewite it as functions so they can be called when needed.

**Comment by rebuilt** [comment]
> The pattern followed so far is first load `lv-config`, then in all other places we read the options in `lv-config` and proceed accordingly. If we wanted to follow that pattern, we need to expose an lvim setting to override `vim.opt` stuff.

That pattern is what we used to do but it got confusing for people.  It was sort of arbitrary what things couldn't be changed with a lunarvim global.  The choice was either to duplicate all settings or none.

**Comment by rebuilt** [comment]
Settings file now has this format

```
local M = {}

M.options = function()
  -- vim.opt related things
end

M.commands = function()
 -- vim.cmd related things
end

return M
```

**Review by Tastyep — APPROVED** [review]
Looks good :+1: 

I just have a minor style suggestion about the method's name, IMO names like `options()` or `commands()` should be used for functions returning something, here I would use a verb.
For example, `load_options()` and `load_commands()`, what do you think ?

**Comment by rebuilt** [comment]
>  For example, `load_options()` and `load_commands()`, what do you think ?

Yeah.  That works.  I changed the names of the functions.

**Review by abzcoding — APPROVED** [review]

**Pull request merged**
