### PR TITLE
lv-vimtex exists but wasn't called, no config was called.

### PR DESCRIPTION
**Pull request by atropos112**
Vimtex wasn't loading the config `lua/lv-vimtex/init.lua `. I'm not sure if this is the best way to do this but it does work.

### CODE REVIEW

**Comment by rebuilt** [comment]
Let's keep init.lua clean and tidy by doing all this in plugins.lua

```
  use { "lervag/vimtex", ft = "tex", config = function() require "lv-vimtex" end }
```

**Review by rebuilt — CHANGES_REQUESTED** [review]
Don't add to init.lua

**Comment by atropos112** [comment]
You are absolutely correct @rebuilt , I tried something similar and forgot to :PackerCompile and :PackerInstall and convinced myself that it didnt work , ill create a pull request for the suggested change in a moment

**Comment by rebuilt** [comment]
Pretty soon, these plugins will be moved out of plugins.lua and into lv-config.lua.  This is already hooked up in master.  So, once it's removed vimtex will need to be added to the custom_plugins table in lv-config.lua

```
O.custom_plugins = {{"folke/tokyonight.nvim"}}
```

**Pull request merged**
