### PR TITLE
Too much text while creating a pull request

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

There is too much text while creating a pull request

## Type Of Change

Please check the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Create a pull request and see the difference
- ...

## Checklist:

- [x] I read the [contributing](https://github.com/ChristianChiarulli/LunarVim/blob/rolling/CONTRIBUTING.md) guide
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by abzcoding** [comment]
@Tastyep what do you think?

**Comment by PZ31k0nauT** [comment]
I generally like this template. One thing I think should be changed are the checkboxes.

Those should only be used for task. If so the maintainers can quickly see if a contributor thinks he/she has all tasks completed.

Otherwise the task-overview for the PR in the PR list is misleading.

**Comment by Tastyep** [comment]
I agree with both comments, we can probably remove the "Type Of Change section" and instead propose some tags to prefix the PR name.
([Feature], [Bugfix], [Breaking])
Should we also make the Checklist  a simple list ?

**Comment by abzcoding** [comment]
> I agree with both comments, we can probably remove the "Type Of Change section" and instead propose some tags to prefix the PR name.
> ([Feature], [Bugfix], [Breaking])
> Should we also make the Checklist a simple list ?

can you do a PR on that :pleading_face:  , I'm too lazy to do so :sweat_smile:

**Comment by abzcoding** [comment]
closed in favor of #876

**Pull request closed without merging**
