### PR TITLE
Explicit stdin for formatters

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

I tried to be smart :facepalm:  and used some weird logic in the formatter `stdin`
there is absolutely no reason for that :sweat_smile:

### CODE REVIEW

**Review by Tastyep — APPROVED** [review]

**Comment by maxxnino** [comment]
Should we use stdin true or false. Which one is better

**Comment by abzcoding** [comment]
> Should we use stdin true or false. Which one is better. If true is better, can you edit zig to stdin=true

the only difference between them is this:

some formatters accept input from stdin:
```
cat my_shitty_code.sth | awesome_formatter -format_my_code (hence stdin = true)
```

some does not:
```
another_formatter -format -file my_shitty_code.sth
```

**Comment by maxxnino** [comment]
> > Should we use stdin true or false. Which one is better. If true is better, can you edit zig to stdin=true
> 
> the only difference between them is this:
> 
> some formatters accept input from stdin (hence `stdin = true`):
> 
> ```shell
> cat my_shitty_code.sth | awesome_formatter -format_my_code
> ```
> 
> some does not (hence `stdin = false`):
> 
> ```shell
> another_formatter -format -file my_shitty_code.sth
> ```

If the formater can handle both. Which one is better.

**Comment by abzcoding** [comment]
> > > Should we use stdin true or false. Which one is better. If true is better, can you edit zig to stdin=true
> > 
> > 
> > the only difference between them is this:
> > some formatters accept input from stdin (hence `stdin = true`):
> > ```shell
> > cat my_shitty_code.sth | awesome_formatter -format_my_code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > some does not (hence `stdin = false`):
> > ```shell
> > another_formatter -format -file my_shitty_code.sth
> > ```
> 
> If the formater can handle both. Which one is better.

the default is ` stdin = true `

**Pull request merged**
