### PR TITLE
Improve commands in README

### PR DESCRIPTION
**Pull request by kidonng**
Sorry for the bad title, I can't think of a better one.

LunarVim is a great project! However I think the commands offered in the README can be improved:

- Remove unnecessary `sudo` usage
- Improve manual compile instructions (do it in a temporary directory)
- Deleting only `site` directory when troubleshooting (so users don't lose history/swap/etc.)
- `-f` is required for `rm` when deleting plugins since `.git` may contain read only files

### CODE REVIEW

**Review by rebuilt — COMMENTED** [review]
Removing only the packer directory works if we are only cleaning up LunarVim files.  There are old issues stemming from conflicting files from other configurations (SpaceVim).   https://github.com/ChristianChiarulli/LunarVim/issues/198#issuecomment-811658134_   Lvim also puts the packer directory elsewhere.  It's easier just to remove the entire nvim directory than to troubleshoot incompatibilities with old installations.

**Comment by rebuilt** [comment]
Everything else looks good.  I learned you don't need sudo when -f will suffice.

**Comment by kidonng** [comment]
> Removing only the packer directory works if we are only cleaning up LunarVim files. There are old issues stemming from conflicting files from other configurations (SpaceVim). [#198 (comment)](https://github.com/ChristianChiarulli/LunarVim/issues/198#issuecomment-811658134)_ Lvim (a different set of configurations) also puts the packer directory elsewhere. It's easier just to remove the entire nvim directory than to troubleshoot incompatibilities with old configurations.

Then I guess removing the entire `~/.local/share/nvim/site` will be enough.

**Comment by rebuilt** [comment]
Ya.  I think you're right.  Deleting the 'site' directory should work.  I tested switching between two different packer configurations.  The trouble was in the 'compile' file ~/.local/share/nvim/site/lua/_compiled.lua. Deleting that file enables packer to do its job correctly.   But I still think we should delete the entire 'site' directory to be safe.  I also tested switching between packer and plug configurations.  In theory, they should never conflict but I just wanted to sanity-check.  Plug creates ~/.local/share/nvim/plugged.  Looks like leaving it in place doesn't hurt anything.

**Pull request merged**
