### PR TITLE
Hook to run PackerCompile during install phase

### PR DESCRIPTION
**Pull request by roobert**
Added a hook to run `PackerCompile` after install - I think this should help prevent some common problems for new users.

This hook could also be used to run `LspInstall lua` which would mean users could use the dashboard to edit their configs without getting errors out of the box, what do you think?

### CODE REVIEW

**Comment by IndianBoy42** [comment]
Is there a reason to only have this on the first run? automatically compiling after installing/syncing seems like a good idea in general isn't it?

**Comment by roobert** [comment]
@IndianBoy42 - I did consider this but I didn't want to change existing behaviour / confuse users that have expectations around how Packer functions

**Comment by luxus** [comment]
this should be fixed in the latest rolling branch

**Comment by roobert** [comment]
@luxus l

**Pull request closed without merging**
