### PR TITLE
(feat) use neoformat as the defalt format option

### PR DESCRIPTION
**Pull request by rafamadriz**
* Get rid of all unnecessary complexity for setting up efm for formatting

* No need for efm server since it's no going to be used for formatting
  (some languages need it for lint, e.g python, if those cases the efm
  server was left and not completely removed)

*  Add `forma_on_save` option and remove all unnecessary format options for specific languages

### Benefits

1. Users can toggle format_on_save for all languages, and not have an option for every single language as it was before.
2. We don't need to worry about setting up formatters with efm anymore (which can be a pain to do)
3. Simplify the config, and get rid of a ton of unnecessary settings for specific languages. We don't have to parse x formatter that an user want to efm or whatever. Just having the formatter you want installed and in your path will work out of the box.

Hey @ChristianChiarulli this is done, and tested in my machine, all working as expected. Take a look a let me know if you want any change (also test this to be 100% sure before merging)

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
Thanks, works great 🎃

**Comment by soerenmartius** [comment]
This doesn't seem to work per default for Terraform anymore? How am I supposed to set autoformat for `*.tf` files on save?

**Comment by rafamadriz** [comment]
> This doesn't seem to work per default for Terraform anymore? How am I supposed to set autoformat for `*.tf` files on save?

Neoformat supports terraform, (see [here](https://github.com/sbdchd/neoformat#supported-filetypes)). You just need to have terraform installed and in your $PATH.

Here how to [install terraform](https://www.terraform.io/downloads.html)

**Comment by soerenmartius** [comment]
@rafamadriz I have terraform installed in my path and I've seen that Neoformat supports terraform also - thanks for that. Anyways, if I save a `*.tf` file, it won't get formated. If I run `:Neoformat! terraform` manually, it works.

**Comment by soerenmartius** [comment]
just to make sure, I have `O.format_on_save = true` set in my config.

**Comment by rafamadriz** [comment]
> just to make sure, I have `O.format_on_save = true` set in my config. Autoformat seems to work on other filetypes such as `*.ts` though.

Okay, I think that I know the problem, can you open a terraform file and do `:set filetype`, what's the output ?

**Comment by rafamadriz** [comment]
hey @soerenmartius I've been testing this and it seems like the autoformatting for terraform files doesn't work correctly. I also tried to set an autocommand for filetype ft, but that didn't work either. I'm not sure why this happens only for terraform.

**Comment by soerenmartius** [comment]
> :set filetype

```
filetype=tf
```

**Comment by soerenmartius** [comment]
> hey @soerenmartius I've been testing this and it seems like the autoformatting for terraform files doesn't work correctly. I also tried to set an autocommand for filetype ft, but that didn't work either. I'm not sure why this happens only for terraform.

btw, when I run `:Neoformat! terraform` it changes the syntax highlighting also

**Comment by soerenmartius** [comment]
Shall I open a new issue for this?

**Comment by rafamadriz** [comment]
> Shall I open a new issue for this?

If you have the time open one in the Neoformat repo, there's nothing wrong in our end. I think the issue is how Neoformat is setting the formatter for terraform files. From what I saw it seems like they are setting literally `terraform`, instead of `ft` which is the output you get when doing `set filetype` in a terraform file. But I'm not sure tho, I may be wrong.

**Comment by soerenmartius** [comment]
Hi, I've opened #782 for further discussion. `nvim-treesitter` uses `hcl` as a filetype which is technically spoken also correct. Neoformat used `terraform` as outlined by you. 

You can see that treesitter also applies the right syntax highlighting when running `:set filetype=hcl`

**Pull request merged**
