### PR TITLE
[feature] Append any terminal executable shortcut with lv-config

### PR DESCRIPTION
**Pull request by barlingo**
In your lv-config do:
lvim.builtin.terminal.execs = {{"lazygit", "gg", "LazyGit"}, {"gdb", "tg", "GNU Debugger"}} 

To add any list of executable shortcuts to be launch by toggleterm. Table structure is
{{exec_path, keymap, name}}

You can also do:
lvim.builtin.terminal.execs[#lvim.builtin.terminal.execs+1] = {"gdb", "tg", "GNU Debugger"}

To append an executable.

# Description

New feature, allows users to configure different terminal commands with shortcuts, and uses lvim terminal to launch them, just like LazyGit.

## How Has This Been Tested?

- Tested on rolling.
- Appended different commands like "gdb" it was correctly added to the list.
- Appended commands not available in the terminal -> shows error correctly.
- Overwritten execs table. Deletes base command "LazyGit"

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
this is a cool idea, I'm going to leave it open until I have time to document it.

**Comment by abzcoding** [comment]
@barlingo can you fix the formatting/linting :pleading_face:

**Comment by rebuilt** [comment]
> this is a cool idea, I'm going to leave it open until I have time to document it.

I'm not sure why we can't just merge it.  It doesn't change the default behavior.  A user doesn't need to do anything different to have LazyGit enabled.  The keybinding stays the same.  As far as the end user is concerned, nothing has changed.    

I tested by adding `lvim.builtin.terminal.active = true`.  

These are the commands I tried

  lvim.builtin.terminal.execs = {{"lazygit", "gg", "LazyGit"},
  {"npm run docs:dev", "zd", "Launch webserver"},
  {"htop", "zh", "Htop"},
  {"ncdu", "zn", "Disk usage"},
  {"python", "zp", "Python REPL"}}

Thanks for this pr!

**Comment by rebuilt** [comment]
The npm thing didn't work.  It's only commands that don't take arguments.

**Comment by rebuilt** [comment]
If you split the string and check only the first word, it works.  You can run a binary and arguments

```
M._split = function(inputstr, sep)
  if sep == nil then
    sep = "%s"
  end
  local t = {}
  for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
    table.insert(t, str)
  end
  return t
end

M._exec_toggle = function(exec)
  local binary = M._split(exec)[1]
  if is_installed(binary) ~= true then
    print("Please install executable " .. exec .. ". Check documentation for more information")
    return
  end
  local Terminal = require("toggleterm.terminal").Terminal
  local exec_term = Terminal:new { cmd = exec, hidden = true }
  exec_term:toggle()
end
```

**Comment by ChristianChiarulli** [comment]
If we can get the argument stuff working then I will merge this,

why does it say infinite changes were made?

**Comment by abzcoding** [comment]
> If we can get the argument stuff working then I will merge this,
> 
> why does it say infinite changes were made?

we are working on it :sweat_smile:

**Comment by abzcoding** [comment]
Github got mental, closing this in favor of #1122

**Pull request closed without merging**
