### PR TITLE
[Feature]: Add possibility to focus nvimtree instead of toggle

### LINKED ISSUE #980: [Feature]: Smarter explorer use
### Feature motivation

I want to switch to nvimtree with a keypress, but current SPC+e, will only toggle.  This means that when I am editing a file and I want to go over to nvimtree, I have to press SPC+e twice.

### Describe the expected solution

Perhaps SPC+e should do different things depending on context:

1) If the user is on nvimtree, it closes
2) If nvimtree is not visible, it opens
3) If the user is on a different window, it switches to nvimtree.

### Describe the alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by williamgoulois**
# Description

Add a new possible behavior to nvimtree :

pseudo-code:
```lua
if (isOpened) then
  if (isFocused) then
    close()
  else
    focus()
  end
else
  open()
end
```

Fixes #980 

## How Has This Been Tested?

Tested with multiple splits, windows.

### To activate follow this steps :

- Set in your lv-config.lua
```lua
lvim.builtin.which_key.mappings.e = {"<cmd>lua require'core.nvimtree'.focus_or_close()<CR>", "Explorer"}
```
- Now `<leader>e` will use this behavior instead of toggle

### CODE REVIEW

**Comment by ichigo-gyuunyuu** [comment]
With the `new_contract` branch merged into rolling, I believe the option to activate it would be 
```
lvim.builtin.which_key = {
	e = { "<cmd>lua require'core.nvimtree'.focus_or_close()<CR>", "Explorer" },
}
```

**Comment by williamgoulois** [comment]
I updated my PR to `new_contract` it is ready for merge

**Comment by abzcoding** [comment]
can you fix the linting/formatting plz 🥺

**Comment by williamgoulois** [comment]
@abzcoding Done 🙂

**Comment by ohechtl** [comment]
This doesn't work for me, throws this error after adding:
`lvim.builtin.which_key.mappings.e = {"<cmd>lua require'core.nvimtree'.focus_or_close()<CR>", "Explorer"}`


```
E5108: Error executing lua [string ":lua"]:1: module 'core.nvimtree' not found:
        no field package.preload['core.nvimtree']No cache entry
        no file './core/nvimtree.lua'
        no file '/usr/share/luajit-2.0.5/core/nvimtree.lua'
        no file '/usr/local/share/lua/5.1/core/nvimtree.lua'
        no file '/usr/local/share/lua/5.1/core/nvimtree/init.lua'
        no file '/usr/share/lua/5.1/core/nvimtree.lua'
        no file '/usr/share/lua/5.1/core/nvimtree/init.lua'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/core/nvimtree.lua'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/core/nvimtree/init.lua'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/core/nvimtree.lua'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/core/nvimtree/init.lua'
        no file './core/nvimtree.so'
        no file '/usr/local/lib/lua/5.1/core/nvimtree.so'
        no file '/usr/lib/lua/5.1/core/nvimtree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/core/nvimtree.so'
        no file './core.so'
        no file '/usr/local/lib/lua/5.1/core.so'
        no file '/usr/lib/lua/5.1/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/oliver/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/core.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
        ```

**Pull request merged**
