### PR TITLE
ray-x/lsp_signature.nvim plugin added and lsp_config.common_on_attach…

### PR DESCRIPTION
**Pull request by PBird**
-- common_on_attach function was missing in ftplugin/typescript.lua and ftplugin/javascript.lua ( fixed )
-- ray-x/lsp_signature.nvim added and configured in default_config and example config. 

image

### CODE REVIEW

**Comment by abzcoding** [comment]
There is already a PR for lsp_signature #672

**Comment by PBird** [comment]
> There is already a PR for lsp_signature #672

I did not see there is pr for it until now. But i have fixed lsp_config.common_on_attach function additionally. and I added plugin different way he did in #672. Owner can decide what he should. thanks for warn :)

**Comment by abzcoding** [comment]
agreed, @ChristianChiarulli in case you wanted to make lsp_signature a builtin plugin, this might be the PR for it

**Comment by nkoturovic** [comment]
Info about `compe` bug that should be fixed: https://github.com/ChristianChiarulli/LunarVim/issues/620#issuecomment-873664016

**Comment by PBird** [comment]
> Info about `compe` bug that should be fixed: [#620 (comment)](https://github.com/ChristianChiarulli/LunarVim/issues/620#issuecomment-873664016)

**Comment by PBird** [comment]
> Info about `compe` bug that should be fixed: [#620 (comment)](https://github.com/ChristianChiarulli/LunarVim/issues/620#issuecomment-873664016)

https://user-images.githubusercontent.com/9611415/124619617-76c98d80-de81-11eb-90aa-e52acc3afdee.mp4

did i miss something. i think there isn't bug ?

**Comment by nkoturovic** [comment]
- I think the problem is when there are multiple suggestions and `compe` stays open for some reason. 
- It used to work with `<CR>` but now I must close it with `<C-e>` which closes `compe` popup.
- <CR> worked the same way before (it was mapped to accept `compe` suggestion and therefore close popup`).

**Comment by abzcoding** [comment]
as describe [here](https://github.com/ChristianChiarulli/LunarVim/issues/553#issuecomment-871892568) we're going to keep core plugins to a minimum and tackle these additions using [LunarModules](https://github.com/ChristianChiarulli/LunarVim/wiki/WIP:-Lunar-Modules) or a LV market place

**Pull request closed without merging**
