### PR TITLE
pull request : readme and some default settings

### PR DESCRIPTION
**Pull request by gnmearacaun**
1. A few additions to the README and lv-config.example
2. in telescope.lua so that the preview is visible on a laptop screen by default
3. set linebreak in default-config so that words aren't divided when wrap is enabled
4. I brightened up the comment color to `gray = #9a9a9a` to make it better for users that have `transparent_window` enabled 

# Description

Please include a summary of the change and which issue is fixed. \
List any dependencies that are required for this change.

Fixes #(issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. \
Provide instructions so we can reproduce. \
Please also list any relevant details for your test configuration.

- Run command `:mycommand`
- Check logs
- ...

### CODE REVIEW

**Comment by gnmearacaun** [comment]
I couldn't get these commands working, but there is probably another way for user to set
```
--O.plugins.telescope.defaults.layout_config.width = 0.50
-- O.plugin.telescope.layout_config.width = 0.95
-- O.telescope.layout_config.preview_cutoff = 60
```

**Comment by rebuilt** [comment]
This pull request is doing too much.  Modifications to the readme should be in a different pr than modifications to default settings.

**Comment by rebuilt** [comment]
I do like the additions to the readme letting people know they can use autocomplete to discover more options.  And the links to the wiki.

**Comment by gnmearacaun** [comment]
Sure, I can change this request and make a separate one for the default-config.

**Pull request closed without merging**
