### PR TITLE
support flutter-tools

### PR DESCRIPTION
**Pull request by pxsanghyo**
- add active flag for flutter-tools
- add autoformat flag

### CODE REVIEW

**Comment by pxsanghyo** [comment]
it's not connecting to dartls when flutter-tools is active.
Can I get some help please?

**Comment by pxsanghyo** [comment]
It's working now

**Comment by barun108** [comment]
Can you share your configs. @pxsanghyo ?

**Comment by pxsanghyo** [comment]
@barun108 you mean lv-config.lua?

```lua
-- dart
O.lang.dart.sdk_path = '/Users/pxsanghyo/.flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot'
O.lang.dart.flutter_tools.active = true
O.lang.dart.autoformat = true
```

**Comment by pxsanghyo** [comment]
@barun108 let me know if it works. cheers

**Comment by barun108** [comment]
> @barun108 let me know if it works. cheers

sure

**Comment by UltimateOmega** [comment]
@abzcoding Can you close this one?
in favor of #974.

**Comment by abzcoding** [comment]
Closed in favor of #974

**Pull request closed without merging**
