### PR TITLE
[Bugfix] Use error instead of print + prevent shadowing

### PR DESCRIPTION
**Pull request by Tastyep**
# Description

What's in the title + the error now sticks better instead of disappearing like a print would.

## How Has This Been Tested?

lv-config: O.toto.tata = true, opening / closing

### CODE REVIEW

**Review by kylo252 — COMMENTED** [review]
Nice idea!

I tried it just now by adding an erroneous value in lv-config:
```lua
O.lang.cp.linter = "clangd"
``` 
But the error message is looking pretty confusing:
```log
Error detected while processing /home/user1/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user1/.config/nvim/init.lua:5: attempt to call local 'error' (a string value)
Press ENTER or type command to continue
```

Maybe we need to parse it slightly differently.

**Comment by Tastyep** [comment]
I guess you reproduced the work instead of checking out the branch, check the error in your log.

**Comment by kylo252** [comment]
> I guess you reproduced the work instead of checking out the branch, check the error in your log.

Yes that was it! I missed the other variable rename `error` -> `err`.
Much better now:
```log
Error detected while processing /home/user1/.cache/LunarVim/init.lua:
E5113: Error while calling lua chunk: /home/user1/.config/nvim/init.lua:5: Configuration error: Vim(luafile):E5113: Error while calling lua chunk: /home/user1/.config/nvim/lv-config.lua:59: attempt to index field 'cp' (a nil value)
```

There's a side-effect though that could be considered a breaking change.  When I used to have such errors before, it was still possible so use neovim relatively fine, but now it looks like it's stopping the loading of a lot plugins completely until you figure out where the issue, assuming you actually know how to resolve it. 

So seeing how `lv-config-example.lua` is not really bullet-proof, maybe should lower the requirement from an error to a warning instead? But generally I think you should define what is considered a "critical" error.

I messed around a bit with `vim.notify` but I couldn't get anything useful from it.

**Comment by ChristianChiarulli** [comment]
let's lower to warning and merge this

**Comment by Tastyep** [comment]
The error() function exits, so the rest of the code wasn't loaded, I agree that it's a too much.
I used notify with the ERROR flag as it asks to press ENTER and allows the user to actually see the error message.
The WARN flag behaves like a print, see [source code](https://github.com/neovim/neovim/blob/master/src/nvim/lua/vim.lua#L416)

**Comment by ChristianChiarulli** [comment]
I feel like the print is still more communicative when testing I will have to do some testing on stream I think.

**Pull request closed without merging**
