### PR TITLE
allows enough time for keybindings to be attached to buffer

### PR DESCRIPTION
**Pull request by rebuilt**
fixes issue #296.  Though I think this setting depends on the speed of the underlying hardware.

### CODE REVIEW

**Comment by rebuilt** [comment]
I should also say that I've changed my personal timeoutlen to 500 because I'm using tpope's surround.vim.  It's hard to type all the keystrokes with only a 200ms buffer.  The same was true for emmet.

**Comment by ChristianChiarulli** [comment]
@rebuilt I've always had this conflict between timeoutlen being fast and the whichkey menu showing up. Btw have you tried emmet-ls?

**Comment by rebuilt** [comment]
Yes.  Had a conversation about it [here](https://github.com/ChristianChiarulli/LunarVim/issues/286)  #286

I had my own personal neovim config and was able to use emmet-ls. I couldn't get it to work with compe.  I had to switch to completion-nvim because it supports chain completion.  I added the required steps in the other thread.  

Yesterday I switched to full time use of lunarvim but I haven't switched the completion plugin from compe to completion-nvim yet.

**Comment by rebuilt** [comment]
Does emmet-ls work out of the box in lunarvim?

**Comment by rebuilt** [comment]
I have changed the whichkey keybinding to \.  It works better for me and I dont have to see whichkey open up when I'm just commenting things out.

**Comment by rebuilt** [comment]
Autocomplete for emmet is bugged.  I don't think it works with compe.  

lunar_emmet

**Comment by rebuilt** [comment]
Looks like the autocomplete is bugged with emmet.  Its probably not compatible with compe; needs chain completion support.

lunar_emmet

**Comment by rebuilt** [comment]
> @rebuilt I've always had this conflict between timeoutlen being fast and the whichkey menu showing up. Btw have you tried emmet-ls?

There will always be a conflict between whichkey speed and the proper functioning of plugin mappings if they are both bound to the leader key.  Whichkey should be on its own key.  If it's the only thing bound to a particular key(like backspace or a function key) ttimeout and ttimeout length will apply.  It's very important for there to be no other mappings, otherwise timeout and timeoutlen apply.  I think ttimeout is already at 50ms in LunarVim.   

https://www.johnhawthorn.com/2012/09/vi-escape-delays/

**Comment by rebuilt** [comment]
To see what's already been set:
```vim
:verb set timeout?
:verb set ttimeout?
:verb set timeoutlen?
:verb set ttimeoutlen?
```

**Comment by rebuilt** [comment]
Never mind.  I just tried it.  Changing the keymappings to '\\' work and whichkey loads instantly but none of the tables populate correctly.  I guess the plugin will only work with the leader key.

**Comment by rebuilt** [comment]
I tested the latest changes you made to Lunarvim.   Looks like emmet works out of the box now.

**Comment by rebuilt** [comment]
Maybe not.  It worked on first load but not anymore.

**Comment by ChristianChiarulli** [comment]
@rebuilt the changes I made should activate snippets (which weren't active before) and emmet-ls should just work out of the box now (after a global install). 

I would love to find a way to decouple which key popup time from `timeoutlen`.

**Comment by ChristianChiarulli** [comment]
@rebuilt the changes I made should activate snippets (which weren't active before) and emmet-ls should just work out of the box now (after a global install). 

I would love to find a way to decouple which key popup time from `timeoutlen`.

**Comment by rebuilt** [comment]
No longer relevant since the switch to lua whichkeys

**Pull request closed without merging**
