### PR TITLE
[Doc] Minimize the pull request template

### PR DESCRIPTION
**Pull request by Tastyep**
pull-request-template-raw
pull-request-template png

### CODE REVIEW

**Comment by Tastyep** [comment]
I'll remove the Tag part since we could use Labels, brb.

**Review by abzcoding — APPROVED** [review]
look wonderful :heart_eyes:

**Comment by Tastyep** [comment]
> look wonderful heart_eyes

Thanks a lot!

Regarding Labels, I can't assign one on my PR. I don't know if it needs to be configured for contributors.
Should we keep it like that in the meantime ?

**Comment by abzcoding** [comment]
> > look wonderful heart_eyes
> 
> Thanks a lot!
> 
> Regarding Labels, I can't assign one on my PR. I don't know if it needs to be configured for contributors.
> Should we keep it like that in the meantime ?

yeah it is good already, we'll figure that out later on

**Pull request merged**
