### PR TITLE
Preserves previous cursor position.

### PR DESCRIPTION
**Pull request by sainivasmangu**
I wanted to add a feature that I remember coming out of the box in vim. The few lines I added preserves the previous cursor position in a file. Saw the code on stackoverflow btw. Since I don't know any lua, I added this code to `vimscript/functions.vim`. Thought it might be useful to others too, so making this PR.

[Link to the stackoverflow answer](https://stackoverflow.com/questions/7894330/preserve-last-editing-position-in-vim)

Thank you :)

### CODE REVIEW

**Comment by arxra** [comment]
Looks like you've kept pushing changes to the branch you used for the merge request :)

**Comment by maxime50** [comment]
You can also use [nvim-lastplace](https://github.com/ethanholz/nvim-lastplace) :)

**Comment by sainivasmangu** [comment]
> Looks like you've kept pushing changes to the branch you used for the merge request :)

my bad... will revert

**Comment by sainivasmangu** [comment]
> You can also use [nvim-lastplace](https://github.com/ethanholz/nvim-lastplace) :)

i didn't know about this... thanks! and any plans on making it a default?

**Comment by maxime50** [comment]
> i didn't know about this... thanks! and any plans on making it a default?

yw! I just saw that someone made a pull request for this already : https://github.com/ChristianChiarulli/LunarVim/pull/477
Btw, implementing this feature by default is a great idea since it's for sure really usefull in many situations! :+1:

**Comment by sainivasmangu** [comment]
> yw! I just saw that someone made a pull request for this already : #477
> Btw, implementing this feature by default is a great idea since it's for sure really usefull in many situations! +1

if you plan on accepting PR #477, I will close this request. I need to make some personal changes😅

**Comment by sainivasmangu** [comment]
> I would like to do it, but I can't because I am not a maintainer smile
> 
> I have no idea if @ChristianChiarulli is the only maintainer but if so, we just have to wait for his opinion about what he would prefer when he have time ^^

'aight then im gonna close this PR. I'm gonna assume he will prefer lua over vimscript...
thanks for the really quick reply :)

**Pull request closed without merging**
