### PR TITLE
Added nvim-lastplace

### PR DESCRIPTION
**Pull request by pard68**
nvim-lastplace is a plug-in that tracks the last cursor location in a file and returns to that location when the file is reopened.

### CODE REVIEW

**Review by ChristianChiarulli — CHANGES_REQUESTED** [review]
this is more than just lastplace, also try to add in extras

**Comment by pard68** [comment]
I noticed that I had screwed up a merge in my fork and fixed it before I saw you had a pending change, sorry about that. :grimacing: 

But ya, all but the one commit were erroneous, I don't know exactly how those got into this branch... but they were for either myself or for a different PR I've made.

**Comment by abzcoding** [comment]
After recent changes to the plugins, I think we can suggest users to add this as a custom plugin
inside `lv-config.lua`:
```lua
O.custom_plugins = {
       {
        'ethanholz/nvim-lastplace',
        config = function()
            require'nvim-lastplace'.setup {
                lastplace_ignore_buftype = {"quickfix", "nofile", "help"},
                lastplace_ignore_filetype = {
                    "gitcommit", "gitrebase", "svn", "hgcommit"
                },
                lastplace_open_folds = true
            }
        end,
        event = "BufRead"
    }

}
```

**Comment by rebuilt** [comment]
This configuration has now been added to the wiki.   https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations#nvim-lastplace  

@ChristianChiarulli I'm not sure if you want this in LunarVim core so I'm leaving it open.

**Comment by luxus** [comment]
can this be closed? lastplace can be now(at the moment in rolling branch) easily installed as a custom plugin

**Comment by abzcoding** [comment]
closed in favor of [O.user_plugins](https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations#nvim-lastplace)

**Pull request closed without merging**
