### PR TITLE
Fix Lint CodeActions + Better dev experience on JS/TS

### PR DESCRIPTION
**Pull request by maxime50**
This makes CodeAction autofixes working

https://user-images.githubusercontent.com/51096534/124395931-e9493a80-dcd4-11eb-9b19-13cb85963f00.mp4

I changed efm to [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) on js/ts files only for now as it's less bloated than efm and it uses built-in neovim sources to provide out-of-the-box functionality. efm's codeActions also doesn't work.

Also added [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils) plugin to get usefull utils like Import all missing imports (exposed as :TSLspImportAll)

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
Looks great 🌵

**Comment by yassinebridi** [comment]
Hey @maxime50, apparently this pull request has been reverted right?
it's such a shame since this makes TypeScript dev experience similar to what we used to have with coc.nvim

**Comment by abzcoding** [comment]
@yassinebridi you can install `https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/` yourself and get the same experience

**Comment by yassinebridi** [comment]
@abzcoding I thought i wouldn't work with the latest changes, thank you, you have been very helpful.

**Comment by abzcoding** [comment]
> @abzcoding I thought i wouldn't work with the latest changes, thank you, you have been very helpful.

in case you wanted help adding it to your `lvim`
https://github.com/abzcoding/lvim/commit/c654785e2eccece5b1690d3e510288c3f63a212b

**Comment by maxime50** [comment]
@abzcoding thanks, you're the best :)

I think this is indispensable for Typescript developers. ^^

They also moved the `nvim-lsp-ts-utils` TypeScript codeAction right inside `null-ls` bultins.

So it could be interesting for lunarvim use it from there also. (if we just want the codeaction for example.)

**Comment by ChristianChiarulli** [comment]
we could probably support the code action natively if it's built into null-ls

**Pull request merged**
