### PR TITLE
[Refactor] nvimtree to be configurable

### PR DESCRIPTION
**Pull request by chaeing**
# Description
Refactor nvimtree to be configurable

## How Has This Been Tested?
lv-config.lua
```
O.plugin.nvimtree.side = "left"
O.plugin.nvimtree.show_icons.git = 0
```

### CODE REVIEW

**Comment by chaeing** [comment]
Hi all.

Is there any specific formatting for the project?
I am on Arch using 'stylua-bin' from AUR

Thanks in advance.

**Comment by Tastyep** [comment]
Hello, thank you for your contribution.

Please check the [contribution guide](https://github.com/ChristianChiarulli/LunarVim/blob/rolling/CONTRIBUTING.md#setting-up-development-tools). You probably forgot to move the .stylua.toml file.

**Comment by rebuilt** [comment]
I'm working on a pr to allow a user to replace the default config with their own.  

```
O.plugin.nvimtree.config = function()
      YOUR_CUSTOM_CONFIG_HERE
end
```

**Comment by chaeing** [comment]
> Hello, thank you for your contribution.
> 
> Please check the [contribution guide](https://github.com/ChristianChiarulli/LunarVim/blob/rolling/CONTRIBUTING.md#setting-up-development-tools). You probably forgot to move the .stylua.toml file.

Thanks, I missed it!
It was actually under /utils not /tools btw.

**Comment by chaeing** [comment]
> I'm working on a pr to allow a user to replace the default config with their own.
> 
> ```
> O.plugin.nvimtree.config = function()
>       YOUR_CUSTOM_CONFIG_HERE
> end
> ```

**Comment by hawkinchina** [comment]
when lvim.builtin.nvimtree.show_icons.git = 1 , why git icons can not display. ?

**Pull request merged**
